### ISSUE TITLE
Issue103 - Save/Download Prompt when Exiting

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#103]
When exiting PEWI, prompt the user to save/download their watershed design.

- Prompts to "save/download" screen from Sandbox and Lessons.
- Prompts to "download multimaps" command window (currently right side task bar), when in Set-Up Multiplayer mode

**Comment by qaws01395** [comment]
[Compatibility problem](https://stackoverflow.com/questions/14645011/window-onbeforeunload-and-window-onunload-is-not-working-in-firefox-safari-o)
