### ISSUE TITLE
Issue106 - Multiplayer map player count

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#106]
Add function so the multiplayer map tool automatically determines how many players/sections of the map exist. Should comprise of the following 3 changes in Multiplayer division mode:
- Function for adding players
- Function for removing players
- Function for automatically calculating how many players have been add in the division toolbar (so user does not need to manually select/adjust, as is currently the case)

**Comment by tomtinkerer** [comment]
Mehul's got this

**Comment by mehulshinde** [comment]
function that let's you add players added. Adding function to remove players.
