### ISSUE TITLE
Issue107 - Move Paint Option

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#107]
Move the two paint options from their current tab to immediately below the left-side toolbar.

Also add a description (a few words max) when you hover over them.

[PaintButtonMovingInstructions.docx](https://github.com/LESEM-PEWI/pewi3.0/files/1004865/PaintButtonMovingInstructions.docx)

**Comment by qaws01395** [comment]
I will look into this.

**Comment by qaws01395** [comment]
build 2 version
on the top
on the bottom
