### ISSUE TITLE
Issue109 - Pick your colors

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#109]
Currently, PEWI overlays maps have a lot of color redundancies. At least within tabs (i.e. Physical Features, Ecosystem Service results), try to minimize color redundancies so individual colors are associated with specific maps.

**Comment by elizabethli1998** [comment]
I will try to look into this one.

**Comment by tomtinkerer** [comment]
While you're at it please add some comments, especially for each cluster of colors. Include verbal descriptions of the colors (maybe on each line), a description for the entire section, and comments for each color set specifying which overlay maps are using them. All of this should make life easier in the future
