### ISSUE TITLE
Issue111 - Soil Type Key Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#111]
When opening the Soil Type overlay map (under Physical Features tab), the key is very long and overflows beyond the bottom of the screen for most PC/browser configurations. Suggest an improvement (i.e. resizing the key box, or selecting a new location for it), run it by me, and then implement the fix.

**Comment by elizabethli1998** [comment]
I will try to look into this.

**Comment by tomtinkerer** [comment]
Update - I did merge, but then reversed the merge. You had it going into master.
