### ISSUE TITLE
Issue118 - Chat/Message Box Overhaul

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#118]
_**Do NOT start on this until Sue is done with #94 , as it overlaps significantly.**_

 In short, the Chat/Message Box needs some major upgrades. Here are some of the problems:
- In Lessons, the prompts (and associated graphics) can be triggered out of order, with either a prompt being skipped, returned to, or both right after one another. 
- Needs to be "made more obvious". Kind of hidden on side, when text changes the player's attention does not move there.
- Index entries are great, but not really integrated into main PEWI interface. The chat box has been brought up as a possible location for these entries, but that also appears to be scope creep. (Fix detailed below.)

Recommended Fixes/These To Do:
- Make the Message Box wider, allowing for more words/line. Sue's #94 should have also decreased the font, which will help.
- Modify the Message Box to be able to contain multiple "Messages" or "Hints", separated by something that sticks out (i.e. bold line, putting messages in bubbles.....experiment and share the results with me). The application for this is in the Levels, where players could benefit from scrolling back to previous prompts.
- Add a second box below the Message Box; title it "Index Info Box", "Background Info", or something similar. Link the contents to the "General" entries for whichever Index entries are pertinent to the player's current screen, selected overlay map, selected Land-Use, or a combination. (Experiment, share with me and articulate your preferences, we'll make a decision.)
[2017_Update_118_Message Box Overhaul.docx](https://github.com/LESEM-PEWI/pewi3.0/files/1012104/2017_Update_118_Message.Box.Overhaul.docx)
               - For Yield/Productivity maps, ensure this includes an explanation of why two land-uses share one map (i.e. Conventional Corn and Conservation corn - same output, same productivity expectations)

UPDATE - Recent updates have also opened up real estate in the bottom-left corner, consider putting "Index Info Box" there.

**Comment by tomtinkerer** [comment]
Recent updates have also opened up real estate in the bottom-left corner, consider putting "Index Info Box" there.

**Comment by elizabethli1998** [comment]
I will look into this.

**Comment by tomtinkerer** [comment]
Great job so far! Requesting the following alterations:
- Please make this window "hide-able" like the dialogue box immediately above it
- In each entry pointing to an Index entry, include a clickable link that takes you directly there
