### ISSUE TITLE
Issue124 - Aggregating multiplayer maps update

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#124]
When aggregating multiplayer maps, allow the user to 
1. See file names for files already added, and
2. Allow for multiple files to be selected/added at the same time (i.e. open folder of only the maps, hit CTRL-A, update all 6 at once)

**Comment by qaws01395** [comment]
Looking into this.

**Comment by qaws01395** [comment]
When I upload random .csv file it causes problem.

![image](https://cloud.githubusercontent.com/assets/7816231/26736188/9e8e9e74-478a-11e7-97f6-719ae812d67d.png)

**Comment by qaws01395** [comment]
So far

![image](https://cloud.githubusercontent.com/assets/7816231/26738623/6f193c4e-4794-11e7-8a7a-36c4f12a271c.png)

**Comment by tomtinkerer** [comment]
OK, it works! With one problem.....

Let's say File 1 is in Folder A, and File 2 is in Folder B. Right now, there is no way to add both. (First add File 1, then add File 2. File 2 will remove File 1 from the list.)
