### ISSUE TITLE
Issue126 - Square/Rectangular Paint Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#126]
Complete the following steps:
- Enter Sandbox, select a new land-use.
- Change paint function to "Square/Rectangular" function. 
- Click ONCE on any viable PEWI tile. Application should start tracking what the square/rectangle will look like depending on where you move your mouse next.
- DO NOT CLICK ON ANOTHER TILE. Instead, go to Land-Uses and select a DIFFERENT land-use. (Not conventional corn, not the one you picked last.

PEWI is still tracking your rectangle/square, even though you changed land-uses. Logically, a user wanting to change land-uses would probably want to start at a new tile. Fix this bug.

**Comment by qaws01395** [comment]
Looking into this.
