### ISSUE TITLE
Issue137 - Multiplayer Player Count Changes/Updates

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#137]
**Wait until #106 is complete**

Add the following 2 functions:
- Ability to combine 2 player's land holdings (i.e. click "Combine", select the two players to merge, then merge together. Remaining players' numbers are redone as needed)
- Autocheck function for blank players/players with 0 PEWI tiles allocated to them
               - Before multimaps can be downloaded, require user to either delete these players, or allocate land to them

**Comment by Xemnaes** [comment]
Looking into this.
