### ISSUE TITLE
Issue141 - Overlay Map Hoover Info Customization - V3.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#141]
Overlay maps currently display (1) tile coordinates and (2) raw score for the map selected. Needs to be modified as follows:

Part I: Add a "User Settings" button below "Options", clicking it should lead to a page like the "Options" page, with the following checkbox toggle ON/OFF options to select from:
- Current Land Cover
- Current Precipitation Level
- Tile Soil Type
- Subwatershed Number (**only on maps where applicable**)
- Selected Overlay Map Raw Score
- Other Variables Related to Selected Overlay Map

Part II: When the user's cursor hovers over a tile, the following information should display (in this order, w/ explanation text where needed):
- Tile Coordinates
- Selected Overlay Map Raw Score
- Current Land Cover
- Current Precipitation Level
- Tile Soil Type
- Subwatershed Number (**only on maps where applicable**)
- Other Variables Related to Selected Overlay Map

Part III: Make the "cursor hoover over tile info" contained within a box w/ background, then show me. (Currently no background, hard to read when running over dark tiles.) Might request additional modifications.

Part IV: Change "Options" button to "Instructor Options"

**Comment by elizabethli1998** [comment]
Looking into this.

**Comment by Xemnaes** [comment]
Issue resolved in development-3.0 branch.
