### ISSUE TITLE
Issue143 - Update Options Page - V3.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#143]
The Options page needs a list of updates.

- Settings on the Options page are not saved in save files. Add them.
- Options page is not updating when Sandbox is exited or entire PEWI application is reset. Either of these should reset it.
- Options page is currently locked under Multiplayer Setup. Unlock and make sure anything changed under it is carried on via divided save files.

**Comment by ueabu** [comment]
Looking into this

**Comment by ueabu** [comment]
Can you explain the last part a little more. " Options page is currently locked under Multiplayer Setup. Unlock and make sure anything changed under it is carried on via divided save files."

**Comment by tomtinkerer** [comment]
First 2 of 3 resolved

**Comment by tomtinkerer** [comment]
Alex, you've got #3 on this list

**Comment by Xemnaes** [comment]
Pull request submitted for #3
