### ISSUE TITLE
Issue147 - Randomization Fix When Land Uses Removed

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#147]
Scenario:
(1) Randomize watershed.
(2) Go to Options, eliminate a land use. Return to main screen.
(3) Eliminated land use is not longer an option to paint with, but is still on the watershed.

Solution:
- When a land use is removed within the Options page, but all PEWI map tiles with that land use default to Conventional Corn.

**Comment by elizabethli1998** [comment]
Looking into this.
