### ISSUE TITLE
Issue150 - Toolbar Update - INCOMPLETE

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#150]
**INCOMPLETELY/DESCRIPTION IN PROGRESS**

Toolbar Update - 
	1. Make Index Button larger, as wide as Toolbar
	2. Add Paint Single, Paint Box, and Undo as 3 separate buttons as a single line (1) between "Index" and Toolbars, and then (2) below Toolbar. Compare design, select one for improvement
	3. Compare: Round corners on boxes vs. Square/flush corners

**Comment by elizabethli1998** [comment]
I will look into this one.
