### ISSUE TITLE
Issue152 - Flyover Freedom Update - V3.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#152]
Currently in PEWI, the user can fly over the map with a fixed focal point in the center. Update this mechanic so the user is free to move in any direction, so long as:
1. the camera stays above ground
2. camera is no more than a logical maximum height above the map
3. camera is restrict to left/right movement that is over the map (camera cannot be "off map" to the left/west, with a clear view of the underneath abyss)

**Comment by tomtinkerer** [comment]
Uma is working on this

**Comment by Xemnaes** [comment]
Issue resolved in development-3.0 branch.
