### ISSUE TITLE
Issue155 - Resizing Bug with Results Page Checkboxes

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#155]
After Sue's mega-commit #154 resolving #94 and #107, this is the only remaining component needing resizing. Fix it please.

**Comment by tomtinkerer** [comment]
Sue is working on this

**Comment by qaws01395** [comment]
Robert, are there any more changes needed in this Issue?

**Comment by tomtinkerer** [comment]
Nope, done!
Do you know what PR resolved this? Reference it in a comment here, so we can track the change if needed in the future

**Comment by tomtinkerer** [comment]
Resolved in a pull request (unsure which) by qaws01395 sometime June 2-20, 2017
