### ISSUE TITLE
Issue156 - Internet Explorer compatibility - V3.1

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#156]
**Do NOT start this until June 12**

Investigate/test PEWI in Internet Explorer and Edge, documenting all observed conflicts/problems. Test this via a simulated server, NOT just be opening the "index.html" file directly in your browser. Once conflicts/problems are documented, begin fixing.

**Comment by qaws01395** [comment]
A suspected problem for this:
The resizable unit "vw, vh, vmax, vmin" is not supported in some browser. Check the following link:

[Viewport units: vw, vh, vmin, vmax](http://caniuse.com/#feat=viewport-units)

**Comment by qaws01395** [comment]
A suspected problem for this:
The resizable unit "vw, vh, vmax, vmin" is not supported in some browser. Check the following link:

[Viewport units: vw, vh, vmin, vmax](http://caniuse.com/#feat=viewport-units)

**Comment by qaws01395** [comment]
looking into this

**Comment by qaws01395** [comment]
[Site scan](https://developer.microsoft.com/en-us/microsoft-edge/tools/staticscan/?url=http%3A%2F%2F34.212.131.98)

**Comment by qaws01395** [comment]
![image](https://user-images.githubusercontent.com/7816231/28440398-b255afea-6d6b-11e7-99ea-e5e576f80848.png)

**Comment by qaws01395** [comment]
I've made some notes here, may be a useful reference to look at in the future.

**Comment by tomtinkerer** [comment]
K note taken. 

STATUS: Done for v3.0, notes on here relevant to v3.1 work
