### ISSUE TITLE
Issue158 - Add Precip Tables to Overlay Yield Maps

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#158]
Yield Overlay Maps have been added displaying individual yield types' dependency on soil type, but not the precipitation component. Add a table that appears near overlay map key when a Yield Overlay Map is selected. You have some freedom in determining how to add this, exactly where to place it, etc., but it should communicate the information found in Table S15 on pg. 35 (second half) of your binder.

**Comment by elizabethli1998** [comment]
I will look into this
