### ISSUE TITLE
Issue163 - New Videos and Entries for Index (EVERYONE, FEEL FREE TO ADD)

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#163]
This issue will serve as a central point for new Index entries and videos to be accumulated. Anything on this list either needs (1) a modification to an existing Index entry, (2) a new dedicated Index entry, (3) a modification to an existing Index video, (4) a new dedicated Index video, or (5) multiple of these changes. ListI have started us out with the following list:
- "Play" guided levels feature (new entry(ies), new video(s))
- Yield overlay maps (new entries, new videos)
- Undo function (add to Functionality/Hotkeys entries. New video will come later after the hotkey overhaul)
- Functionality/About (consider alterations to highlight existence of the new email form)
- Results Panels update/modification (AFTER Result graphics overhaul)

More to come. This issue will not be closed until after all core changes for V3.0 are complete and evaluated.

**EVERYONE ON THE TEAM: FEEL FREE TO ADD COMMENTS/THINGS TO THE LIST AS YOU MAKE ADDITIONS TO THE CODE**

**Comment by qaws01395** [comment]
I feel like it might be convenient to have introduction video about 

- Aggregate multiplayer map functionality can be used under what situation (i.e. team project assignment)

**Comment by tomtinkerer** [comment]
Go through videos and add the following where applicable (will likely be to a lot of them):
1. Add images to accompany equations
2. Add variable table to equations
3. Add highlighting feature to variable tables and variables within equations
4. Some videos appear to be "zoomed out", creating a lot of blank black space. Please fix this.

**Comment by tomtinkerer** [comment]
**In addition to the changes above**, I have reviewed the videos on our YouTube account and come up with the following suggestions:

Woody Biomass Yield - Good
Phosphorus Pollution Control - Good.
Erosion Control - Good.
Mixed Fruit and Vegetable Yield Advanced - Good.
Switchgrass Yield Advanced - Good. Spelling Error in video title. (no capital "G")
Grass Hay Yield Advanced - Good.
Cattle Yield Advanced - Good.
Alfalfa Hay Yield General - Good.
Topographic Relief Advanced - Good.
Sediment Retention - Good.
Nitrate Pollution Control - Good.
Switchgrass Yield - Good.
Wood Yield Advanced - Good.
Wood Yied - Good.
Mixed Fruit and Vegetable Yield - Good.
Cattle Yield - Good.
Alfalfa Yield Advanced - Good.
Soybean Yield Advanced - ERROR. Has audio for "corn yield advanced"
Soybean Yield - Good.
Corn Yield Advanced - Good.
Corn Yield - Good, but need another sentence. After the first sentence ends w/ "No difference between yields in conventional and conservation systems", add a sentence or extend that was to cite what studies we drew this conclusion from. It is possible the most argued assumption throughout the model.
Yield Advanced - Good.
Yield - Remake. "Yields are calculated either using existing case studies or equations tied to the Iowa Corn Suitability Rating" for your opening sentence; feel free to tweak as needed.
Sediment Retention - Good.
Phosphorus Retention - Good.
Nitrate Retention - Remake video, changing the last half. "...It also harms aquatic ecosystems by depleting oxygen both in local waterways and the Gulf of Mexico."
Water Quality - Add more photos...but with taste, of course. Should go without saying, but we are not putting an example of Blue Baby Sydrome in the video.
Erosion Control - Good.
Carbon Sequestration Advanced - Good.
Carbon Sequestration - Good.
Soil Quality - Large gap at beginning, please reduce.
Game Wildlife Advanced - Good. (Make sure to add table here.)
Game Wildlife - Good.
Biodiversity Advanced - Good. (Make sure to add table here.)
Biodiversity - Good.
Habitat - Good.
Modules - Good.
Crop Rotation - Good.
Management Practices - Good.
Precipitation - Good.
Corn Suitability Rating - Good.
Soil Texture - Considering redo, at the very least put pictures in of different soil types as mentioned.
Soil Class - Good.
Hydrologic Group Advanced - Goood, but need More pictures.
Hydrologic Group - Good.
Drainage Class - Good. (Consider adding a table.)
Subwatershed Boundaries - Consider rewrite. Run this by Lisa for her suggestions.
Strategic Wetland - Good.
Flood Frequency - Good.
Topographic Relief - Good.
Main Menu - Good.
Guided Play - Good.
Keyboard Shortcuts - Good, but will need to be redone once Uma's flyover update goes through.
Pause Menu - Good.
Multiplayer Mode - Good.
Save Watershed - Good.
View Perspective - Good.
Comment Panel - Good.
Data Sheet - Good. Add some highlighting.
Annual Yield Graph - DELETE. We will be deleting this graph
Precipitation Graph - Good.
Ecosystem Services Graph - Redo once Yield category is integrated.
Land Use Graph - Good.
Results Panel - Good. Change Youtube title to "Results Tab"
Tool Panel - Redo, include new overlay maps.
Navigating the PEWI Workspace - Good.
Functionality - Good.
Conventional Corn - Good, but add a picture of a corn cob (or pile of them).
Conventional Corn Advanced - Good.
Alfalfa Advanced - Good.
Conservation Corn Advanced - Good.
Conservation Forest Advanced - Good.
Conservation Soy Advanced - Good. Change from "Soy" to "Soybean" in title (no need to remake video)
Conventional Forest Advanced - Good.
Conventional Soy Advanced - Good. Change from "Soy" to "Soybean" in title (no need to remake video)
Grass Hay Advanced - Good.
Mixed Fruit and Vegetable Advanced - Good.
Permanent Pasture Advanced - Good.
Prairie Advanced - Good.
Rotational Grazing Advanced - Good.
Short Rotation Wooody Bioenergy Advanced - Good.
Switchgrass Advanced - Good.
Wetland Advanced - Good.
Land Uses Advanced - Good.
Land Uses - Good.
Alfalfa - Good.
Conservation Corn - Good.
Conservation Forest - Good.
Conservation Soy - Good, change to title "Conservation Soybean". No need to redo video.
Conventional Forest - Good.
Conventional Soy - Good, change to title "Conventional Soybean". No need to redo video.
Grass Hay - Good.
Mixed Fruit and Vegetable - Good, Change title to "...Vegetables"
Permanent Pasture - Good.
Prairie - Good.
Rotational Grazing - Good.
Short Rotation Woody Bioenergy - Confirm/verify the rotation time for aspen. Video says "10", part of me suspects it might be "7". But I could be wrong.
Switchgrass - Good.
Wetland - Good.

**Comment by tomtinkerer** [comment]
Additional new videos required:
1. Yield efficiency overlay maps (one for each)
2. Additional Management Practice entries 
       A) create one for each of the five assumed practices in Conservation Corn and Soybean
       B) create one for each practice listed in the Conventional/Conservation Forest land-uses. (Mentioned in the videos, likely in binder as well). Should be approximately 4-7
       C) Saving and Running a User Simulation

Do **NOT** make a video for "Optimizing PEWI Goals", as this feature has some major work yet and will likely be hidden for V3.0 release.

**Comment by tomtinkerer** [comment]
And everyone, as always, feel free to add more where needed

**Comment by tomtinkerer** [comment]
**Short Rotation Woody Bioenergy Advanced" entry and video are missing

**Comment by tomtinkerer** [comment]
In PEWI, please change "Nitrate Pollution Control" in the Index to "Nitrate Pollution". Change the Youtube video titles to reflect this as well (no need to remake videos)
