### ISSUE TITLE
Issue164 - Hotkey Customization Interface/Page - V3.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#164]
Create a page where the user can set custom hotkeys to specific actions. A couple requirements to point you in the right direction:
- Each "Action" should be tie-able to **TWO** hotkeys
- Each key can only be tied to **ONE** action

I recommend starting this once #152 is done or close to done.

**Comment by Xemnaes** [comment]
Looking into this.

**Comment by Xemnaes** [comment]
Issue resolved in development-3.0 branch.
