### ISSUE TITLE
Issue165 - Results Graphics Page Overhaul - V3.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#165]
As per our team discussion with Lisa, the Results Graphics page needs some changes.
- Graphic Slot #1 (Land-Use percentages/acres) is fine, DO NOT CHANGE
- Graphic Slot #2 (currently Ecosystem Services spider diagram) should be changed as follows:
       - make this slot a changeable graphic slot, with 2 choices (i.e. how Slot #1 changes between years, or "categories"/"list")
       - Part A (default view) of this slot should be similar to PEWI V2.1 "Scores" graphic
       - Part B of this slot should be the current Ecosystem Services spider diagram, but with another leg for "Total Sum Yields" that adds all yield scores (0-100) together. It might be possible for this score to exceeds 100 under rare circumstances......design/build accordingly

Note: Current Yield-only spider diagram will be **deleted**.

**Comment by ueabu** [comment]
Looking

**Comment by tomtinkerer** [comment]
The following pushed to #281 ::

Graphic Slot #2 (currently Ecosystem Services spider diagram) should be changed as follows:
- make this slot a changeable graphic slot, with 2 choices (i.e. how Slot #1 changes between years, or "categories"/"list")
- Part A (default view) of this slot should be similar to PEWI V2.1 "Scores" graphic
