### ISSUE TITLE
Issue166 - V2.1 File Compatibility Error, Years 2 and 3 eliminated - V3.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#166]
When loading a .json save file from PEWI V2.1, the current V3.0 loads in Year 1 but then does not show years 2 and 3. Mehul and I suspect the years are loaded, but not shown. This bug is ALSO affecting save files with multiple years of data. Please fix!

**Comment by mehulshinde** [comment]
Also, the files from V3.0 too can't load year 2 and year 3.
