### ISSUE TITLE
Issue174 - Remove player option bug

### ISSUE THREAD

**Issue by Xemnaes** [LESEM-PEWI/pewi3.0#174]
In Sandbox, the "reset" button from multiplayer setup is present. Remove this button from sandbox mode.

**Comment by Xemnaes** [comment]
Fixed. Issue will be resolved with next pull request.

**Comment by tomtinkerer** [comment]
Has this made it in to development yet?

**Comment by Xemnaes** [comment]
This issue will be resolved after the Issue#181 pull request.

**Comment by Xemnaes** [comment]
After syncing my development branch, it appears that this issue was fixed by another pull request. This issue is now closed.
