### ISSUE TITLE
Issue175 - Randomization in Simulation Bug

### ISSUE THREAD

**Issue by Xemnaes** [LESEM-PEWI/pewi3.0#175]
When replaying a user experience and the user toggles the randomization button, the simulation doesn't randomize the board. Implement this function.

**Comment by Xemnaes** [comment]
Fixed. Issue will be resolved with next pull request.

**Comment by tomtinkerer** [comment]
Updated Issue number

**Comment by tomtinkerer** [comment]
Has this made it in?

**Comment by Xemnaes** [comment]
This issue will be resolved after the Issue#181 pull request.

**Comment by Xemnaes** [comment]
Issue is now fixed with the Issue#181 pull request. Closing issue thread.
