### ISSUE TITLE
Issue 194 - Issue #182 Left Tool Bar Bug - V3.0

### ISSUE THREAD

**Issue by elizabethli1998** [LESEM-PEWI/pewi3.0#194]
After some merging, it appears that the Left Tool Bar now has a few bugs such as:

- Icons are enlarging and turning into square shapes when clicked on

- The details lists and map keys have disappeared, leaving the information for them to be crammed onto the toolbar

Not sure how exactly this happened. Perhaps it was due to some merge conflicts that messed it up or something.

**Comment by elizabethli1998** [comment]
Looking into this one, as I discovered it just now.

**Comment by qaws01395** [comment]
I think I know what will cause these.  But I didn't see these happen on the current development branch. I can tell you what to do if these happen again.

**Comment by elizabethli1998** [comment]
This has been fixed in Issue#147
