### ISSUE TITLE
Issue229 - Small bug for Merging multiplayer 

### ISSUE THREAD

**Issue by qaws01395** [LESEM-PEWI/pewi3.0#229]
Disable the escape key functionality when user operates merging players.
Also when there's only 1 player then disable the merge button.
Maybe can change a little bit of the design of merging button. 👍 
When the left console slide in, it should remain there or disappear instead of  slide in (?

**Comment by Xemnaes** [comment]
Looking into this.

**Comment by Xemnaes** [comment]
Pull request submitted
