### ISSUE TITLE
Issue236 - Bug: Issue141 

### ISSUE THREAD

**Issue by qaws01395** [LESEM-PEWI/pewi3.0#236]
1. After making disable some instructor hover info options, and click Escape key again, both options page and escape menu open on the screen.

2. On left console, some icons are selected but not reflecting that "ones" are the ones user clicked on.

3. If it was in grid painter mode, after performing disable instructor hover info and go back to sandbox, painter will itself choose a tile to paint and wait for finishing grid painting.

**Comment by ueabu** [comment]
Looking into this

**Comment by ueabu** [comment]
Looking into this

**Comment by ueabu** [comment]
Fixed

**Comment by ueabu** [comment]
Properly fixed.
