### ISSUE TITLE
Issue263 - Removing Landuses Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#263]
1. Open PEWI
2. Randomize Year 1 landuses
3. Switch to Year 2, make some changes (i.e. a giant block of Mixed Fruits & Vege)
4. Switch to Year 3, randomize landscape.
5. Go to Options, eliminate Convention/Conservation Corn and Soybean, as well as Mixed Fruits & Vege
ERROR/BUG: PEWI removes these options from the toolbar and the **currently selected year**, but does not **remove from Year 1 and Year 2** (observe: the giant block of Mixed Fruits & Vege in Year 2 is still present, despite that landuse no longer being an option)

**Comment by Xemnaes** [comment]
Pull requested submitted.
