### ISSUE TITLE
Issue #272 - Index Titles Overflowing

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#272]
The following Index Titles are overflowing, as shown in attached screenshots.:
- Functionality/**Nativating the PEWI Workspace**
- Functionality/Nativating the PEWI Workspace/**Ecosystem Services Graph**
![image](https://user-images.githubusercontent.com/11810901/28792946-00b2d3a0-75f7-11e7-9f5b-a0701cfb83d9.png)

- Modules/Yield/**Short Rotation Woody Biomass**
![image](https://user-images.githubusercontent.com/11810901/28792987-264d721e-75f7-11e7-8e2e-0bf026a448d5.png)

**Comment by qaws01395** [comment]
oh I thought you were talking about pewi logo

**Comment by Xemnaes** [comment]
Pull request submitted.
