### ISSUE TITLE
Issue #295 - Physical Features map keys overflow slightly onto PEWI map

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#295]
Make them SLIGHTLY less wider (approximately 5-10% less wide)

![image](https://user-images.githubusercontent.com/11810901/29181593-63b7006c-7dc1-11e7-8d50-38acf774c182.png)

![image](https://user-images.githubusercontent.com/11810901/29181599-67715b80-7dc1-11e7-9282-a6584adfa9e4.png)

**Comment by tomtinkerer** [comment]
@elizabethli1998 is working on this

**Comment by elizabethli1998** [comment]
Should be good to go now.

**Comment by tomtinkerer** [comment]
We just discussed another change, will close once that is pushed/accepted
