### ISSUE TITLE
Issue #301 - Default Setup

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#301]
- Open PEWI, Open Sandbox
![image](https://user-images.githubusercontent.com/11810901/29182930-6a4e5fc4-7dc6-11e7-8394-177112016c0e.png)
- Randomize watershed.
- Go to Main Menu
- Open Sandbox
![image](https://user-images.githubusercontent.com/11810901/29182943-747de424-7dc6-11e7-9b6c-40c62cb849b6.png)

ERROR: watershed shed be 100% conventional corn, but is randomized

**Comment by tomtinkerer** [comment]
Alex you've got this one

**Comment by Xemnaes** [comment]
After updating my development branch with my recent pushes, it appears this issue was fixed when fixing an issue with user sim randomizing.

**Comment by tomtinkerer** [comment]
OK great to hear :)
