### ISSUE TITLE
Issue #302 - Save Bug has Resurfaced

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#302]
Save Files are not loading years 2 and 3

**Comment by Xemnaes** [comment]
Currently looking into this, what I've found:
- The save file retains the land use for each year, even if it doesn't load it

This means there is an error when the file is being loaded, currently investigating.

**Comment by Xemnaes** [comment]
Issue has been fixed. The error stemmed from a change in length of the CSV file (most likely from the option saving update). This caused the uploadCSV method in helpersFE.js to not record data down for each tile, which would allow it to determine how many years have to be added in the sandbox.

**Comment by Xemnaes** [comment]
Pull request submitted.
