### ISSUE TITLE
Issue #303 - Multiplayer Division Combine Error

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#303]
- Add all 6 players with some assigned land. 
- Select "Combine Players"
- Try to click on map
![image](https://user-images.githubusercontent.com/11810901/29183153-3e7b49d8-7dc7-11e7-9a87-a26198f86f47.png)

ERROR: Assign ownership should not be changeable until "Merge" button is clicked

**Comment by Xemnaes** [comment]
Looking into this.

**Comment by Xemnaes** [comment]
Pull request submitted.
