### ISSUE TITLE
Issue #316 - Multiplayer Merging 3+ Players

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#316]
- Set up a multiplayer division with 6 players
![image](https://user-images.githubusercontent.com/11810901/29194486-757f0758-7def-11e7-9c12-18101c4f2320.png)

- Select "Combine Players", then select 3+ players (example: Players 2,3,4)
![image](https://user-images.githubusercontent.com/11810901/29194509-8f51eb1e-7def-11e7-9ae2-00c0bff58c13.png)

- Click Merge
![image](https://user-images.githubusercontent.com/11810901/29194525-9ea9bc4a-7def-11e7-8f36-7d38c8a39560.png)

ERROR: Many things wrong with this image. Please fix

**Comment by Xemnaes** [comment]
Looking into this.

**Comment by Xemnaes** [comment]
Pull request submitted.
