### ISSUE TITLE
Issue320 - glossary document URL changing

### ISSUE THREAD

**Issue by qaws01395** [LESEM-PEWI/pewi3.0#320]
Noticed that the in print function page, url of glossary document will show our project structure.
For security and categorized purpose, it's better to put in doc folder or find a way not showing url (post method).
![image](https://user-images.githubusercontent.com/7816231/29198827-00e5d188-7e0d-11e7-86d2-04dc422576ec.png)

**Comment by tomtinkerer** [comment]
Good catch!
