### ISSUE TITLE
Issue339 - V3.0 Tutorial Videos - V4.1

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#339]
@elizabethli1998 

Produce 2 videos, similar to what we have for V2.1

- A shorter video approximately 60-120 seconds (1-2 minutes)
- A longer, more detailed video approximately 210-330 seconds (3.5-5.5 minutes)

**Comment by NicolasDelacruz** [comment]
On my to-do list.

**Comment by tomtinkerer** [comment]
Riggs is starting on this Wednesday

**Comment by tomtinkerer** [comment]
Riggs has the short tutorial done or close to it, currently working on long tutorial

**Comment by tomtinkerer** [comment]
Riggs finished producing his tutorial videos. However, the old ones are still active and the only ones on the PEWI YouTube account. Add these new videos to the YouTube account and update links in the PEWI application and on the PEWI website to point there.
