### ISSUE TITLE
Issue348 - Fix Print Function Browser Issues - V4.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#348]
**Problem:** Print function works perfectly, but has a lot of browser security conflicts. It works under the right settings within Firefox, but otherwise tends to freeze PDF print page renderings. This is the #1 issue I have been receiving email about; we need to make users aware of this, in leue of a complete compatibility fix.

**Fix:** Add a text bubble/box on the Print page (suggested location attached), that says the following (and feel free to modify/improve my text, if you see fit):

---------------------------------------------------
"ATTENTION USERS: This page is known to have problems with different computer/browser combinations. For best performance, following these steps:
(1) SAVE your PEWI session.
(2) Open PEWI in FIREFOX.
(3) Click the "Lock" icon in the top-left corner, next to your URL. Click the ">" arrow and select "Disable protection for now". This will restart the PEWI, and allow required PDF building scripts to run.
(4) Proceed to Sandbox, upload your PEWI save file, and proceed to Print via this page. "

**Comment by Xemnaes** [comment]
This error is due to a "Mixed Content" warning being generated from parts of the page's content still using HTTP instead of HTTPS.

One can read more about it here: [](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)

A quick search in the GitHub repo reveals ~30 links without the HTTPS protocol. Replacing "http" with "https" at these locations _should_ resolve the issue.

**Comment by WeijiaZhao** [comment]
- ALL print options are not working in current LESEM-development repo, 
- Errors occurred when trying to print "Land Use Charts", "Ecosystem Services Charts" and "Precipitation Charts" in the "Results" section.

**Comment by tomtinkerer** [comment]
Might be resolved, need to test on a server visited through browser (not local hosted file)

**Comment by tomtinkerer** [comment]
Resolved. Was two problems - one we resolved and another that arose for referenced repository was moved to another source URL. Updated URL and now it works.
