### ISSUE TITLE
Issue349 - Precip Levels Not Saving

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#349]
PROBLEM: Precipitation levels are not saving or being saving in during file loads. Tested and confirmed on multiple rigs.

SOLUTION: Find the bug, and fix it. I believe this functionality was working earlier, so it's likely a conflict with newer code.

**Comment by jawadmrahman350** [comment]
Have taken a look and this works.

**Comment by tomtinkerer** [comment]
Thanks for verifying!

@Xemnaes
