### ISSUE TITLE
Issue354 - Save File Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#354]
This is technically two bugs, one very minor and one significant (has impacted multiple users). Combined due to similarities and crossover potential.

1. Save bug, file not loading properly.
     - Open PEWI in Firefox. Create a design with 3 distinct years. Download the save file with the **SAVE AS** option. Title is something unique (i.e. "PEWI_SaveAs")
     - Download the save file again, but this time using the **OPEN** option. Then, save the file to the same folder previously used (usually Downloads), naming it something like "PEWI_Open". Ensure the file type selected is CSV.
     - Open each save file in PEWI. You will observe that "PEWI_Open" does not load years 2 and 3.
2. Save file "bug"
     - Open PEWI, create any design. Download save file. Open file in Notepad.
     - You will observe that Row #1 of data is actually tacked on to the end of the headings row.

Suggested path for fixing:
1. Compare the files and identify what is causing this bug. Then see if we can make the save file format "resistant" to this alteration in the future. (This bug impacted about 25% of students in a class this Spring semester, so it does need to be fixed.)
2. Pretty straight forward - fix it. Mostly visual, though it may have something to do with part 1

**Comment by WeijiaZhao** [comment]
I'll take this.
