### ISSUE TITLE
Issue357 - Update Result Diagrams

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#357]
We need to add another graphic to the Results Graphics page. The graphic should look very similar to the interactive "Scores" graphic in PEWI 2.1. You are free to approach this in whichever way you see fit - I recommend starting by looking for existing similar tools that utilize the PEWI 3.0 graphics package (D3).

PEWI 2.1 can be accessed via the PEWI project website.

**Comment by NicolasDelacruz** [comment]
On my to-do list.
