### ISSUE TITLE
Issue358 - Add Topographic Relief Overlay Map

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#358]
Topography is currently scored in a categorical manner with the following ranges:
- 0-1%
- 1-2%
- 2-5%
- 5-9%
- 9-14%
-14-18%

A visual demonstration of this can be found in PEWI 2.1 under "Physical Features" and "Topographic Relief".

Duplicate this map as an Overlay Map in PEWI 3.0; house it under the "Physical Features" tab in the toolbar.

**Comment by mrkerr** [comment]
I'll take care of this
