### ISSUE TITLE
Issue359 - Limited Wetlands to Flat Areas

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#359]
Topography is currently scored in a categorical manner with the following ranges:

0-1%
1-2%
2-5%
5-9%
9-14%
-14-18%

A visual demonstration of this can be found in PEWI 2.1 under "Physical Features" and "Topographic Relief". (Another issue has already been created to add a map like this to PEWI 3.0)

Using this information, restrict Wetland placement to cells with 0-1% slope. When a user hovers over or attempts to a place a wetland in an unsuitable cell, display a message that reads "Not flat enough for a wetland."

**Comment by jawadmrahman350** [comment]
I'm on it.
