### ISSUE TITLE
Issue360 - Update Strategic Wetlands Map

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#360]
****DO NOT START UNTIL #359 IS COMPLETE AND ACCEPTED TO DEVELOPMENT BRANCH***

- Update the Strategic Wetlands overlay map to have the following categories:
        - Not Suitable (use existing color)
        - Suitable (Use a lighter shade of the color currently used by "Strategic")
        - Strategic (use existing color)
- Add a map key

**Comment by jawadmrahman350** [comment]
I'm on it.
