### ISSUE TITLE
Issue364 - Changing Land Use on Overlay Maps Should be Visible

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#364]
Open "Sandbox", go to Physical Feature maps, select any of the maps. Start dropping in a few Land Uses - you will notice they stay visible on the overlay map until you switch to another map. _**THIS IS CORRECT/DESIRED.**_

Now go to the Scores overlay maps and attempt the same thing - you will see the changed Land Uses do NOT stay visible. Change this so these maps function the same as the Physical Feature maps.

**Comment by jawadmrahman350** [comment]
Submitted for testing.
