### ISSUE TITLE
Issue367 - BUG - HTTP/HTTPS Conflict

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#367]
Alex found what he suspects to be the root cause of several loading errors - some parts of PEWI are not using HTTPS protocols. Fixing this could be as simple as changing referenced links from "http://..." to "http://...". 

Investigate this - if it helps, most conflicts resulting from this should be in the Print page, specially under Print Preview function. Reference Issue #348 and Alex's followup comment for additional details.

**Comment by jawadmrahman350** [comment]
Working on this currently.
