### ISSUE TITLE
Issue368 - BUG - Fix Instructor Options "Reset" Button

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#368]
Open "Sandbox", go to the "Home" menu, select "Instructor Options", make a few changes, then scrolls down to the button and click "Reset Options". This is supposed to reset all buttons and hotkey setting on the page to default settings - however, nothing happens. Fix this.

**Comment by NicolasDelacruz** [comment]
I will work on this.
