### ISSUE TITLE
Issue369 - Replace "Index" with "Glossary"

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#369]
The Glossary was originally called the "Index", but not all references of this old title have been removed. Change the following references from "Index" to "Glossary":

- Bottom Right "Index Box". Every time something is selected in the toolbar (tab, overlay map, etc), the text in this box changes. Nearly all of them currently suggestion the user go to the "Index". ***Note: From now on we will refer to this as the "Glossary Box".
- Click on the Glossary button. The title image still says "Index". Fixing this might require rebuilding the image, depending on how it's stored.
- Within the Glossary, check Functionality/Navigating the PEWI/Index Information Box. Change (1) the name of this entry to "Index Information Box" (appears three times: on outline, in header, and in text), and (2) change every reference to "Index" within the text. Do not worry about the YouTube video.
- In the Glossary, under Functionality/Pause Menu, change "index" to "glossary".

**Comment by WeijiaZhao** [comment]
I'm working on it.
