### ISSUE TITLE
Issue371 - Separate "Contact Us" and "Info"

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#371]
Currently, the "Info/About" and "Contact Us" sections are combined in one pop-up window, accessed by clicking the "info" button at the Top Right corner of PEWI. 

- Leave the Info/About context here, do not alter.
- Make a new button next to Info for "Contact Us", with the current contact form moved into it. You are free to choose an icon - perhaps a "mail"/"letter" icon, or the "speech" icon currently used on the text box center-right side of PEWI.

**Comment by WeijiaZhao** [comment]
Working on it
