### ISSUE TITLE
Issue372 - Update Text Box Icons

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#372]
_**START AFTER #371 COMPLETE**_

Currently:
- Contact Us icon is a speech bubble
- Game Details box (right side, center) icon is a speech bubble
- Suggestion box (right side, bottom) icon is a book with bookmark.

CHANGE TO:
- Contact us icon is a speech bubble (no change)
- Game Details box (right side, center) icon is book with bookmark (change)
- Suggestion box (right side, bottom) icon is a help/question mark button (change)

**Comment by WeijiaZhao** [comment]
Working on it
