### ISSUE TITLE
Issue376 - Limit Precip to Years Currently Active

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#376]
_**START ONLY AFTER #355 IS COMPLETE**_

Precipitation is currently visible for Years 0,1,2,3 regardless of how many years have been selected by the user. Change this so 

- Years 0 and 1 are always shown, and Years 2 and 3 are only shown when the user enables them.
- If all a year is deleted, delete that precipitation level. 
      - Years 1 and 2 have designs and are active. Year 1 precip = 32.16, Year 2 precip = 28.18.
      - Year 1 gets delete. Year 1 now have the design that used to be Year 2, and Year 1 precip now = 28.18.

**Comment by WeijiaZhao** [comment]
I'll take this.

**Comment by jawadmrahman350** [comment]
I'm on it.

**Comment by jawadmrahman350** [comment]
Dona and ready to be tested.
