### ISSUE TITLE
Issue380 - Toggle Corn/Soy Best Management Practices ON/OFF - V4.1

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#380]
This issue involves toggling a collection of Best Management Practices (BMPs) assumed to be included in Conservation Corn and Conservation Soybean on and off. It contains a few components:
- Add a "Alter Assumptions" popup window that allows the user to **_TOGGLE_** these BMPs on and off. 
- Each BMP is already tied to specific variables - you and I will discuss this in depth in a design session and clarify all constraints.
- BMP toggle setting need to be added to the Print function.

**Comment by jawadmrahman350** [comment]
On this.

**Comment by tomtinkerer** [comment]
Jawad basically fixed this. It was waiting on Lisa and I to get back to him on some assumptions/conclusions that had to be made about different BMPs in Conservation Corn and Conservation Soybean. We'll be implementing it into the main code shortly.

**Comment by tomtinkerer** [comment]
This is in reserve. I'll have these numbers finalized shortly after returning in two weeks.

**Comment by tomtinkerer** [comment]
Again in reserve. Infrastructure is not set up for most of this issue, possibly good candidate for next development cycle.
