### ISSUE TITLE
Issue385 - BUG - Too Many Maps Loaded into Multiplayer

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#385]
Loading too many maps and maps that overlap creates a usable PEWI map, but the method through which they are combined is unclear. Establish a protocol for resolving these conflicts:

1. Notify the user there is a conflict between "Map __ and Map __". Ask where to (a) cancel/return to the upload window or (b) to declare a "Priority Map" that will override conflicting cell in the other map.
2. Map are compared two at a time, a composite made, and then the composite compared to the next map.  I.e. 1 and 2; 1/2 hybrid and 3; 1/2/3 hybrid and 4; etc.

**Comment by WeijiaZhao** [comment]
I'm on it.
