### ISSUE TITLE
Issue386 - Multiplayer Results Page

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#386]
Open PEWI, go to Multiplayer setup, add a few players, click Results. The Results pages need to be changed as follows:

**Results Graphics:
- 1st graphic (pie chart) stays
           - REMOVE "Change Years" arrows
           - REMOVE "To Categories" button 
           - CHANGE the key to include Player Numbers
- 2nd graphic (spider diagram) - REMOVE
- 3rd graphic (precipitation) - STAYS/DO NOT ALTER

**Results Table
- Land Use Category - CHANGE title to "Players"
           - REMOVE all current data fields
           - CHANGE to the Players and their respective parcel sizes
- Ecosystem Service Indicator/Measurement - REMOVE
- Other Parameters
           - Precipitation - STAYS/DO NOT ALTER
           - Strategic Wetland - CHANGE to a counter of how many Strategic Wetland cells each player has

**Comment by NicolasDelacruz** [comment]
On my to-do list.
