### ISSUE TITLE
Issue387 - Multiplayer Years and Precipitation Levels

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#387]
Multiplayer setup needs to have the following improvements done:

- Precipitation settings - currently set to default to 24.58 in each year. CHANGE this to randomize, as in the standard SANDBOX configuration.
- The Years tab was previously removed. ADD a new Years tab that only allows for a drop-down selection of how many years to simulate. This will allow teachers/instructors to select how many years the file will include WITHOUT changing land ownership year-to-year.
-Update Save File to Include How Many Years to Load

**Comment by jawadmrahman350** [comment]
I'm on it.

**Comment by WeijiaZhao** [comment]
I'm on it

**Comment by tomtinkerer** [comment]
Also fixes load bug where years 2 or 3 would not load if top left cell in conventional corn
