### ISSUE TITLE
Issue388 - Multiplayer Merging Too Many Maps - Precip Levels

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#388]
_**DO NOT START UNTIL #385 IS COMPLETE**_

Merging multiplayer maps also means PEWI must decide which precip levels to choose - ask the user to either (a) select one map to use the levels from or (b) select custom precip levels.

**Comment by WeijiaZhao** [comment]
I'll take this since I'm working on fixing maps merging bugs.

**Comment by tomtinkerer** [comment]
![image](https://user-images.githubusercontent.com/11810901/42760051-af8334fc-88ce-11e8-943e-3bc20773c455.png)

The text is not accurately displaying file names
