### ISSUE TITLE
Issue409 - Bug with Year Deletion

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#409]
@jawadmrahman350 

Related to #355 

@WeijiaZhao found a bug in year deletion. Add ONLY Year 2, then delete it. Gives a "Year 3 has been moved to Year 2" message, Year 2 is left unchanged. Only happens once. Please investigate and fix.

**Comment by jawadmrahman350** [comment]
Hi, this issue is solved.

**Comment by tomtinkerer** [comment]
#355
