### ISSUE TITLE
Issue411 - Toolbar Sliding Tab Title Fix

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#411]
Open PEWI, select an overlay with a key (i.e. yield efficiency maps), then hover over toolbar tabs. Currently, the tab titles slide BEHIND the map keys. CHANGE this so the title slide IN FRONT of the map keys.

#391 

@WeijiaZhao

**Comment by WeijiaZhao** [comment]
I'll take this
