### ISSUE TITLE
Issue453 - Fix Short-Rotation Woody Biomass Yield Key - 4.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#453]
Key currently says range is 608.6 tons/acre/yr. This is incorrect.

It should be 22.4 Mg/ha/yr, which translates to **24.69 tons/ha/yr**. Change it to this.

**Comment by tomtinkerer** [comment]
Paul has this claimed.

**Comment by paullicata** [comment]
Just calculated with @tomtinkerer - should be 9.99 tons/acre/year.
