### ISSUE TITLE
Issue460 - Update Tracking Function - v4.1/v4.2

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#460]
Some of our additions this summer were not integrated into tracking. This should include:
- Progress Bars (hovering)
- The Customize Menu (unsure if this is even covered at the moment)
- Toolbar hovering effects.
- Copying/Delete years
- New overlay maps
- Hovering over particular cells
- Print function
- New results graphics
- Econ module graphics and tables (including hover and click effects)
- Prompt to end recording session when exiting.

This is a list of what I could think of in the moment - please review updates from over the summer to ensure we've covered all changes.

**Comment by saveripal** [comment]
[Issue460-Update Tracking Function.docx](https://github.com/LESEM-PEWI/pewi3.0/files/3237871/Issue460-Update.Tracking.Function.docx)

**Comment by saveripal** [comment]
[Issue460-Update Tracking Function.docx.pdf](https://github.com/LESEM-PEWI/pewi3.0/files/3237880/Issue460-Update.Tracking.Function.docx.pdf)

**Comment by tomtinkerer** [comment]
@saveripal has been working on this massive issue for a while, and is just about done.
