### ISSUE TITLE
Issue467 - Update General and Advanced PDFs of Glossary Definitions - v4.1/v4.2

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#467]
Can be implemented in either v4.0 or v4.1.

Change "Index" to "Glossary" in these two documents.

**Comment by jbweiland** [comment]
Jared has claimed this.

**Comment by tomtinkerer** [comment]
Lisa and I have decided to remove these, for now (until updated in the future)
