### ISSUE TITLE
Issue: Printing not working with canvg graphics

### ISSUE THREAD

**Issue by mrkerr** [LESEM-PEWI/pewi3.0#471]
Fix by replacing lines (in index.html):

<script type="text/javascript" src="http://canvg.github.io/canvg/rgbcolor.js"></script>  
<script type="text/javascript" src="http://canvg.github.io/canvg/StackBlur.js"></script>
<script type="text/javascript" src="http://canvg.github.io/canvg/canvg.js"></script>

with:
      
<script src="https://cdnjs.cloudflare.com/ajax/libs/canvg/1.4/rgbcolor.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/stackblur-canvas/1.4.1/stackblur.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/canvg/dist/browser/canvg.min.js"></script>

**Comment by tomtinkerer** [comment]
Added to current Master/Live version v3.1 via commit e1fa3653ba31eea61c222585acd14166c1598b78

**Comment by tomtinkerer** [comment]
Added to current Development branch v4.0 via commit fc0a4e7b7251a32c9ba939d0d6c951bf9f2a58f3

**Comment by tomtinkerer** [comment]
Fully implemented. Good job!
