### ISSUE TITLE
Issue476 - Min/Max Value Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#476]
Go to Instructor Option, click "Set Min-Max Values". In one row (i.e. Game Wildlife), type "10" under min and "90" under max; this cause equivalent values to be calculated for the "Actual Min" and "Actual Max" columns. Now click in the cell for "Actual Min", but do not type anything. You will notice it accepts by default a "0" value, and change "Min" to 0. **This should only happen if a valid value (non-zero) is entered.**

**Comment by tomtinkerer** [comment]
Paul has this.

**Comment by paullicata** [comment]
Expanding Issue to include correcting for values entered outside of possible range. I.e if new max < min then new max = old max.
