### ISSUE TITLE
Issue477 - Print Function Reordering and Re-Titling

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#477]
In the Print function, make the following changes:
- Change "Levels Map" to "Result Maps"
- Change "Features Map" to "Feature Maps"
- Change "Yields Map" to "Yield Maps"
- Change "Strategic Wetlands" to "Wetland Suitability"
- Reorder the button clusters as follows:
       Land Use Type Map
       Features Map
       Yield Maps
       Result Maps
       Results
No need to update the PDF generation file yet. That will be another issue. #478

**Comment by TheThirdNut** [comment]
I will take this on.
