### ISSUE TITLE
Issue483 - Locked Precip Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#483]
IF PRECIP IS OFF, the following bug appears
	Copy year 2 to year 1
	Does not change precip
	Save the file
	Load the file new
	Shows precip as copied

Only the land uses should be copied. Fix this.

**Comment by TheThirdNut** [comment]
I believe this is a copying error actually changing the precipitation when it shouldn't have the ability to. We just cannot see the change. (not anything to do with saving and/or loading.)

**Comment by HameisterEric** [comment]
I'm on it.
