### ISSUE TITLE
Issue485 - Customize Save & Exit Button

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#485]
In Customize, the Save & Exit button currently is locked to the bottom of the page. Make this a floating button. You have some creative leeway in implementation, but please run ideas by me first.

**Comment by tomtinkerer** [comment]
Jared has claimed this

**Comment by jbweiland** [comment]
The reset options button will float as well. It will be underneath the Save & Exit button.
