### ISSUE TITLE
Issue493 - Remove Land Use Bug

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#493]
When a land use is removed via the Customize page, the following should occur:
- Code checks if that land use is currently being used anywhere on the map. If no, continue. If yes, the user is prompted with "One or more land uses you have deactivated are currently used on the map. What would you like to replace them with?", with a drop-down selection of the remaining available land uses to pick from.
- The any cells with the deactivated land use(s) are changed to the selected land use.
- These changes are applied to all active years.
- Code checks what land use is current selected by the user (for painting with the cursor). If the selected land use has been deactivated, replace with the first available land use.

**Comment by HameisterEric** [comment]
I'm on it.

**Comment by tomtinkerer** [comment]
Appears to work fully. However, you're changes are cascading and breaking many hotkey controls: definitely R, T, and Q, possibly all of them. Please fix.
