### ISSUE TITLE
Issue501 - Progress Bar Flash Effect

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#501]
Although the Progress Bars are updating appropriately when cells are changed, these changes can be very small and hard to notice. Add two flash effects to each bar when it changes: green when increasing, red when decreasing.

You have some flexibility in deciding how to implement this 
- the shade of each color (ensure it works with all three PEWI backgrounds)
- the size of the effect. Is is outline only? Does the label flash? Does a rounded square surrounding the entire row flash? Try a couple combinations and see what works best.

**Comment by jbweiland** [comment]
Jared has claimed this.
