### ISSUE TITLE
Issue503 - Change Main Tabs Order

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#503]
In the main PEWI map view, the tabs on the left toolbar order as follows:
- Land Use Types
- Precipitation
- Years Selection
- Result Maps
- Physical Features
- Yield Base Rate

Change to the following order:
- Land Use Types
- Physical Features
- Yield Base Rate
- Year Selection
- Precipitation
- Result Maps

**Comment by jbweiland** [comment]
Jared has claimed this.
