### ISSUE TITLE
Issue511 - Black Screen Has Returned

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#511]
Jared was able to recreate the Black Screen, a bug that used to occur more frequently. In the past it occurs when data fields were incomplete. Jared was only able to recreate this bug in an overlay map.

Run an extensive battery of tests on the overlay maps - try your best to break them. Document via comments any tests that yield a Black Screen, and then attempt to fix them. This will require some investigation.

Note: If you attempted to recreate this but couldn't, please leave a comment describing what you tried

**Comment by HameisterEric** [comment]
I believe that this had to do with the previous not calculating results bug(especially when copying a year), but not 100% certain. I looked through the coloring code, and at first glance it seems like all cases are covered. Although if some of the values were not calculated yet (like when copying a year did not calculate) some of the screens would have resulted in all black (which I tested). I am not saying its impossible to produce an all black screen, but an easy way of reproducing has already been removed.
