### ISSUE TITLE
Issue518 - Year 0 bugs

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#518]
When year 0 is added the location that it is added to the years tab doesn't align with anything.
Also, while in year 0 (year 0 selected) you are unable to drag your mouse with a land use type to paint on to the watershed.

**Comment by HameisterEric** [comment]
I'm on it.

**Comment by HameisterEric** [comment]
I am no longer on it.

**Comment by tomtinkerer** [comment]
@HameisterEric What's the status on this issue? Did we finish it or just relegate to "unimportant"?
