### ISSUE TITLE
Issue531 - Economics Module Infographic 1

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#531]
Create the first infographic for the economics module as described in the meeting. This will be the baseline for others to come so do it well.

**Comment by HameisterEric** [comment]
I'm on it

**Comment by tomtinkerer** [comment]
Core merged, still waiting on some edits

**Comment by tomtinkerer** [comment]
@HameisterEric did you ever push edits for this graphic??

**Comment by HameisterEric** [comment]
I did push a number of edits, however it doesn't have some of the features of the other graphic that I had made, such as auto disabling things that appear irrelevant due to the data(it being 0)

**Comment by tomtinkerer** [comment]
@HameisterEric  OK thanks for the update. Finish your current issue and then move on to this one
