### ISSUE TITLE
Issue532 - Improper use of icons

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#532]
Many of the icons that are in use reference the creators of the icons in the comments(commented code), but by looking at the proper use agreement, many if not all of them require to be physically shown somewhere on the website. This will involve finding all the icons that are pulled from else where (hopefully all of them are commented) and giving proper acknowledgement according to each use agreement. This should be done in the info tab.

**Comment by jbweiland** [comment]
I'll work on this.
