### ISSUE TITLE
Issue541 - Resizing while in fly over mode

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#541]
This is very likely low priority.
Many ways to recreate, but the easiest to see the result follows like this:
To recreate:

1. Change size of screen
2. Enter fly over mode(press Q)
3. Change size of screen back
4. Exit fly over mode(press Q) to likely see a wider version of the PEWI map that may no longer fit on the screen depending on how much you resized.

**Comment by tomtinkerer** [comment]
Very low priority. Closing because it is not important at the moment.
