### ISSUE TITLE
Issue542 - Customize hotkey options

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#542]
There are a few things that I noticed about the customize hotkey part of the options page.

1. There is a button for "create multiplayer maps" which doesn't seem to do anything when the button is pressed. The creation of multiplayer maps can be accessed from the main menu
2. The options that say rotate don't actually rotate but move in a direction instead
3. The options that say Pivot also just move in a direction

This will be updated with how this should be fixed, for now it is simply a documented bug.

**Comment by jbweiland** [comment]
I'll take this.

**Comment by jbweiland** [comment]
Bullets 2 and 3 were resolved in the hot keys have gone whack issue.

**Comment by jbweiland** [comment]
This issue is done.
