### ISSUE TITLE
Issue543 - Unable to Move Camera

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#543]
When the camera is angled at certain angles, the camera cannot move in certain directions.

To recreate:

1. Rotate approximately 90 degrees (by holding right mouse button) so that you are looking at the map sideways
2. Try moving in both left and right directions (using the A and D buttons), only one of the directions will work depending on which direction you rotated.

Take a look at the code and see what is causing this and fix this issue.

Without looking at the code, I am guessing that there was supposed to be a max of a direction you could move, but if you recreate this bug you will be able to see that it is not working properly (As you can move infinitely in 1 direction, but not at all in the other).

**Comment by jbweiland** [comment]
I'll take this.

**Comment by jbweiland** [comment]
When rotating around 90 degrees I am able to move infinitely left or right. When I rotating 180 degrees I can initially moved both left and right, but once the map begins to move of the screen, I am not able to move the map toward the center of the screen.

**Comment by jbweiland** [comment]
Eric and I both looked at this and cannot find the code that is currently controlling the movement and adding the current restrictions that are working. I tried adding restrictions to the z axis which resulted in the map rotating when it hit the boundary I set. I am switching to a different issue.

**Comment by tomtinkerer** [comment]
Chalking this up as a minor bug, as so few people will actually encounter it. Thanks for your investigation
