### ISSUE TITLE
Issue585- Print Results Error Out

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#585]
When an Infographic is selected in the "Results" section of the print tab the save and/or preview will fail due to errors depending on the selected graphic.

EDIT: This error does not occur on firefox, but it does on Chrome and Internet Explorer. I am not entirely sure if it has to do with us hosting a local server or if we actually have a problem supporting these browsers.

EDIT2: It appears that the precipitation graphic does not work on firefox.

**Comment by tomtinkerer** [comment]
EDIT2 has been resolve.

The core issue has also occurred in Chrome. We've thrown about 120+ work hours at it and still no solution. Closing, as we've chosen to ignore it and instead include the disclaimer on that print function stating "PEWI'S PRINT FUNCITON WORKS BEST IN FIREFOX"
