### ISSUE TITLE
Issue588- Clunky Scrolling in Glossary

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#588]
Each list item in the glossary is scrollable. Each item is just a single row of words, Scrolling down on each item only lets you view the padding on wide screen. On a thinner screen you need to scroll down just to see the entirety of the words. There already is a major scroll bar there shouldn't be a need to smash items in a particular height. This bug appears to only affect certain browsers.

![image](https://user-images.githubusercontent.com/16964225/62148672-c7143a00-b2bf-11e9-894e-45b763afcd32.png)

**Comment by jiankailee** [comment]
jian working on it
