### ISSUE TITLE
#Issue617 Multiplayer does not work

### ISSUE THREAD

**Issue by HameisterEric** [LESEM-PEWI/pewi3.0#617]
It is impossible to setup multiplayer, there are many bugs that need to be fixed and need to be looked into.

**Comment by tomtinkerer** [comment]
I'm doing recon on this, don't touch until I'm done

**Comment by HameisterEric** [comment]
Well it seems to at least mostly work after I got rid of a typo. Havent fully tested but I was able to setup multiplayer.
#618

**Comment by tomtinkerer** [comment]
Multiplayer division now works perfectly! However, after loading a multiplayer divided map file, land use selection and change is not working - individual, box, randomize, everything gives "NOT FOUND". Fix this please!
