### ISSUE TITLE
Issue622 - Tab Title Change

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#622]
Currently, one tab title reads "Yield Base Rate".

Change this to "Yield Base Rates".

**Comment by tomtinkerer** [comment]
![image](https://user-images.githubusercontent.com/11810901/62959447-707a2600-bdbe-11e9-91e3-9dca370af916.png)

**Comment by jbweiland** [comment]
I'll do this.
