### ISSUE TITLE
Issue623 - Update Result Maps Units

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#623]
Currently, the following Result Maps are in metric units. 
- Corn Grain
- Soybean
- Mixed Fruits and Vegetables
- Alfalfa
- Grass Hay
- Switchgrass
- Wood

Change all of these to English units. This will require changing numbers in 2 locations **for each map:** 
(1) keys
(2) hover effects

**Comment by jbweiland** [comment]
I'll do this.

**Comment by jbweiland** [comment]
For the third color in the wood key, an image that has a black border is being used. This isn't really a big deal, but I just think it doesn't look very good. I am wondering if we can change this to the image with no border.

**Comment by jbweiland** [comment]
We changed the image to match the others.

**Comment by jbweiland** [comment]
This is done.
