### ISSUE TITLE
Issue633 - Results Table Not Aligned

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#633]
Go to the Results Tables page. The first and second table should be aligned - they have the categories and approximately text width, yet are not aligned. Fix this

![Untitled](https://user-images.githubusercontent.com/11810901/63050687-4a798200-bea1-11e9-9c4e-68cda0bdaed3.png)

**Comment by jbweiland** [comment]
I'll do this.
