### ISSUE TITLE
Issue637 - Result Econ Graphics Formatting

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#637]
All graphics need the following changes/updates, where appropriate:
- y-axis with dollar values should include (1) commas designating thousands/millions etc. and (2) dollar signs.
- Hover effects should includes (1) commas designating thousands/millions etc., (2) dollar signs, and (3) two decimal points (designating cents)

**Comment by jbweiland** [comment]
I'll do this.
