### ISSUE TITLE
Issue687 - Econ Button/Tab titles

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#687]
- Swap the icons
- title the first "Economics Graphics"
- title the second "Economics Tables"
- Make both title disappear/appear on hover (as the first two do)

**Comment by tomtinkerer** [comment]
Looks good, but with two small bugs. 

![image](https://user-images.githubusercontent.com/11810901/80559732-25cc2880-89a4-11ea-84ec-a5ff01b12384.png)

Why is a random "s" appearing just behind the image?

![image](https://user-images.githubusercontent.com/11810901/80559757-38466200-89a4-11ea-85ef-3aa4d838f2c3.png)

Text not aligned like other buttons' hover effects.

**Comment by nbatwara** [comment]
@tomtinkerer weird. Both seem to be browser issues it seems. Although, on my computer both Firefox (which you're using I guess) and Chrome are giving me the same results. 
The 's' is from Economic(s) that is breaking over into the second line. 

**Result on my computer on Firefox -** 
<img width="1680" alt="Screen Shot 2020-04-28 at 11 56 45 PM" src="https://user-images.githubusercontent.com/14866671/80562059-28cb1700-89ac-11ea-851d-5be0c0fea9fd.png">

**Comment by tomtinkerer** [comment]
Interesting. We'll ignore for now unless it starts appearing on many more computers than mine
