### ISSUE TITLE
Issue691 - Add Commas to Formatting for Progress Bars

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#691]
As title describes

**Comment by nbatwara** [comment]
@tomtinkerer can you provide more detail on this?

**Comment by tomtinkerer** [comment]
![image](https://user-images.githubusercontent.com/11810901/80625603-11734480-8a13-11ea-8e3b-a0925f9fe30c.png)

In the Progress Bar hover effect, there are no commas separating out the thousands marks.
