### ISSUE TITLE
Issue694 - Title Icon Update

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#694]
Within the PEWI application, top right corner shows "PEWI" "3". Change this to "PEWI" "4". (Might have to create a new image file.)

**Comment by nbatwara** [comment]
@tomtinkerer What typeface is being used for the logo? Also, any specific tool being used to generate the PNG?

**Comment by tomtinkerer** [comment]
We used Illustrator or Photoshop - think it was Illustrator.  Software is on a few computers in the lab, mine for sure. (Matt is using my old work station now, try the intern computers before using his please)

Typeface - let your creative juices flow.

**Comment by nbatwara** [comment]
This can be closed now.
