### ISSUE TITLE
Issue714 - Progress Bar Hover Effect Background Disappeared

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#714]
See image below. The hover effect on the Progress Bars used to have a background, but it has mysterious disappeared. Please fix this. 

![image](https://user-images.githubusercontent.com/11810901/80624904-fbb14f80-8a11-11ea-99c1-c0b2fee13b6e.png)

**Comment by tomtinkerer** [comment]
Test and let me know if this happens for you. I haven't been able to recreate - guessing it might have been a browser issue resolved by clearing cache

**Comment by nbatwara** [comment]
I guess it's a browser issue. I can see the background on mine. 

<img width="1643" alt="Screen Shot 2020-06-09 at 8 30 05 PM" src="https://user-images.githubusercontent.com/14866671/84220480-21f5f080-aa90-11ea-9037-cc369d852c33.png">
