### ISSUE TITLE
Issue716 - Add Watershed Profitability Total

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#716]
Add the total watershed profitability in the following location:
Either above or below the progress bars. Test both and place it where you think looks better.

![Screenshot(2)](https://user-images.githubusercontent.com/11810901/84326632-039cfd00-ab43-11ea-9e39-3d59647944ba.png)

**Comment by nbatwara** [comment]
@tomtinkerer is this related to #701?

**Comment by tomtinkerer** [comment]
@nbatwara Yep you were right, change the description to reflect this.
