### ISSUE TITLE
Issue753 - Add Aquatic Scores to Ecosystem Service Bubble Graphics

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#753]
Add the following entries to the bubble graphics, as shown in photos. Use a placeholder value of 50(%) for now.

**Comment by nbatwara** [comment]
Note: 

- [ ] Change Biodiversity to Land Biodiversity
- [ ] Add Stream Biodiversity (goes below Land Biodiversity)
- [ ] Add Aquatic Health ( Goes below Sediment Delivery)
