### ISSUE TITLE
Issue754 - Update Results Table

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#754]
Update the Results Table with aquatic variables as shown in picture. Use 50(%) as a value placeholder for now.

![image](https://user-images.githubusercontent.com/11810901/115201053-7f989780-a0ba-11eb-884f-f06c3ac96174.png)

**Comment by nbatwara** [comment]
Note: 

- [ ] Change Biodiversity to Land Biodiversity
- [ ] Add Stream Biodiversity (goes below Land Biodiversity)
- [ ] Add Aquatic Health (Goes below Sediment Delivery)
