### ISSUE TITLE
Issue755 - Add Progress Bars for Aquatic Health

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#755]
Add two new progress bars with the names and locations shown in photo. Use 50(%) as a temporarily placeholder value.

![image](https://user-images.githubusercontent.com/11810901/115201213-aeaf0900-a0ba-11eb-8526-63d52c2d163a.png)

**Comment by nbatwara** [comment]
Note: 

- [ ] Change Biodiversity to Land Biodiversity
- [ ] Add Stream Biodiversity (New bar - goes below Land Biodiversity)
- [ ] Add Aquatic Health (New bar - Goes below Sediment Delivery)
- [ ] Remember to add options for the new progress bars in the customize menu.
