### ISSUE TITLE
Issue93 - Customizable Print Function - V3.0

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#93]
PEWI needs a print function, where the user can select from an array of options to include in a printed report and then print (most will "print", then save as PDF). It has been discussed for 2+ years but never fully built.

Action Items/Requirements:
- Noah Hagen (nlhagen) was supposed to start work on this, though he may have ended while still in the design stages. Look at his profile and see if anything was added about a print function. (It would be his most recent branches, was the last thing he worked on before leaving PEWI)
- The Print Function needs to be more like an menu of check-boxes, where the user can select what to and what not to include in the printed report. Here is what I believe to be an exhaustive list:

1. Standard frontal image of watershed design. Default to showing Precipitation on the left toolbar.
2. Result pages graphics, all of them. (Consider adding checkbox for each individually.)
3. Result pages tables. all of them. (Consider adding checkbox for each individually.)
4. Result overlay maps (Nitrate, Erosion, Phosphorus). (Consider adding checkbox for each individually.)
5. Repeat 1-4 for each Year.
6. Physical Features Maps, add checkbox for each.
7. Each entry in the Index, add checkbox for each.

NOTE:  For each larger category (i.e. Index entries), make the list of checkboxes a dropdown. This way users automatically either decide to (1) include or (2) not include the entire section, as most will not pick and choose individual entries.

CONSIDER: Having four basic packages to pick from: (1) Basic Report, (2) Comprehensive Report, (3) PEWI Watershed Information, and (4) PEWI Watershed Information with Glossary. Having these four button will cover nearly all default printing collections/options.

**Comment by tomtinkerer** [comment]
Mehul's got this

**Comment by qaws01395** [comment]
Put here as a note to refer to:
http://blog.stahlmandesign.com/export-html-to-pdf-how-hard-can-it-be/

**Comment by mehulshinde** [comment]
adding sgv to canvas:
https://github.com/canvg/canvg

**Comment by qaws01395** [comment]
Take it if you need in the conference. PDF functionality so far.
[pewi.pdf](https://github.com/LESEM-PEWI/pewi3.0/files/1107289/pewi.pdf)

**Comment by qaws01395** [comment]
Continue working on 

1. reset button
2. precipitation info
3. naming file

**Comment by qaws01395** [comment]
Continue working on 
1. result table
