### ISSUE TITLE
Issue94 - Adjust size auto-scaling for main PEWI map at opening

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#94]
Currently PEWI appears to open at a preset size, likely pixel based. Investigate and adjust so this is auto-scaled based on individual computer/browser/screen size.
- Apply to images
- Apply to toolbars
- Apply to text (front size, margins, etc.)

**Comment by tomtinkerer** [comment]
Sue's got this

**Comment by qaws01395** [comment]
TODO
1. Set minimum size for left/right console.
2. Resizable all the left console: Precipitation, Year selection, Level, Feature, Setting.
3. Resizable result iframe.
4. Fix the two columns land icon.

**Comment by qaws01395** [comment]
Esc Key - Menu
1. Resize the buttons
2. Resize Contents 
  - Index: resize the iframe 
  - Option: resize the buttons
  - Main Menu

**Comment by qaws01395** [comment]
Main Menu

1. Sandbox: **in progress**
2. Play
- Resize buttons on Select difficulty page
3. Utilities
- Resize the buttons first
- Design a level: don't think the content need to be resize
- Multi-player: don't think the content need to be resize
- Aggregate Multi-map: Resize the buttons

**Comment by qaws01395** [comment]
TODO
1. The bar at the bottom
2. IE
3. Index button
4. undo button
5. #111 Move the detail list
6. Left console height
7. Utility - multiplayer map icon

**Comment by tomtinkerer** [comment]
- IE compatibility is being tabled for the moment, will make it into Github Issues list as another issue.
- Checkboxes on Results pages were the only PEWI component with sizing/alignment challenges remaing. Sue is currently pursuing a fix. Creating new issue dedicated to this.
