### ISSUE TITLE
Issue97 - Yield Productivity Overlay Maps

### ISSUE THREAD

**Issue by tomtinkerer** [LESEM-PEWI/pewi3.0#97]
Create a third category of overlay maps for yield productivity (currently have Physical Features and Ecosystem Services Results overlay maps, you will need to make a third tab). Should include one map for each yield type:
- Corn Grain
- Soybeans
- Mixed Fruits and Vegetables
- Cattle
- Alfalfa Hay
- Grass Hay
- Switchgrass Biomass
- Wood
- Short Rotation Woody Biomass

Create categories for individual colors according to "Base Rate Yields". Within each yield type, individual base rates are associated with soil types.

**Comment by elizabethli1998** [comment]
Assigned.
